### ISSUE TITLE
django-ckeditor security issue

### ISSUE THREAD

**Issue by ittbattlesship** [ppfeufer/aa-forum#192]
While updating my server I noticed a warning about a potential security risk regarding the editor used by aa-forum.

"WARNINGS:
?: (ckeditor.W001) django-ckeditor bundles CKEditor 4.22.1 which isn't supported anmyore and which does have unfixed security issues, see for example https://ckeditor.com/cke4/release/CKEditor-4.24.0-LTS . You should consider strongly switching to a different editor (maybe CKEditor 5 respectively django-ckeditor-5 after checking whether the CKEditor 5 license terms work for you) or switch to the non-free CKEditor 4 LTS package. See https://ckeditor.com/ckeditor-4-support/ for more on this. (Note! This notice has been added by the django-ckeditor developers and we are not affiliated with CKSource and were not involved in the licensing change, so please refrain from complaining to us. Thanks.)"

Is there any chance of this being replaced by another editor like Aloha in the future?

This isn't much of a concern for me in particular, as those with edit permissions are trusted members of our group. However, the fact remains that it could potentially be used by threat actors.

**Comment by ppfeufer** [comment]
Ya, that's because there is an older version of jQuery bundled with the editor that is not loaded. And they wanna sell their LTS version of course.

With that said, the next version will have CKEditor 5, but will be released for AAv4, since I'm already preparing for that release and don't want to do all the work twice. See » https://github.com/ppfeufer/aa-forum/pull/181

ETA is probably a month or two. But don't quote me on that one.

**Comment by ittbattlesship** [comment]
That's fair. I'm waiting for the v4 stable release before I upgrade my server, so that will work out just fine for me. Thanks for the update!

**Comment by ppfeufer** [comment]
This has been remedied with v[2.0.0](https://github.com/ppfeufer/aa-forum/releases/tag/v2.0.0) for Alliance Auth v4.

Please read the update instructions.
