### ISSUE TITLE
500 error after topic created on django admin panel

### ISSUE THREAD

**Issue by Rhaven1** [ppfeufer/aa-forum#47]
tried to create a new topic through the admin panel and used the slug Dreadnought-Implant-Sets which seemed successful,  then it went to the giving the 500 error
it was created with locked and stickied selected in the admin panel. 

searching the logs did not see any errors that were just related to the forum. 

tried deleting the topic from the admin panel and it still gives the 500 error and  will not  log into the forum module.   

With the debug on this is the error we get: 

AttributeError at /forum/
'str' object has no attribute 'username'
Request Method:    GET
Request URL:
Django Version:    3.1.13
Exception Type:    AttributeError
Exception Value:
'str' object has no attribute 'username'
Exception Location:    /home/allianceserver/venv/auth/lib/python3.8/site-packages/aa_forum/templatetags/aa_forum_user.py, line 27, in main_character_name
Python Executable:    /home/allianceserver/venv/auth/bin/python3
Python Version:    3.8.10
Python Path:
['/home/allianceserver/myauth',
 '/home/allianceserver/myauth',
 '/home/allianceserver/venv/auth/bin',
 '/usr/lib/python38.zip',
 '/usr/lib/python3.8',
 '/usr/lib/python3.8/lib-dynload',
 '/home/allianceserver/venv/auth/lib/python3.8/site-packages']
Server time:    Sun, 05 Sep 2021 13:10:19 +0000

**Comment by ppfeufer** [comment]
Yes, I can confirm, this will cause an issue. I'll make all entries in the Django admin being read-only with then ext release to prevent this from happening again.

What happens here is, you create a topic without messages. Now when you open the forum index, the topic is there but no messages (last_message, first_message and so on). This leads to an error. Simply removing the topic doesn't solve it, because the Board model also expects to have the messages set to it.

So what you can try now is:
- Open your admin backend and go to Topics
- Find all topics that have a message count of 0
- Remove all those

Open your SQL console or PhpMyAdmin or whatever you prefer
- Open the `aa_forum_board` table. You'll see at least one entry that has no `last_message_id`
- Set a last message ID here. (pick the last one from the `aa_forum_message` table for example)
- Open your forum and navigate to the board you just changed
- Pick the latest topic and add a message
- Remove the message again

This should set the correct `last_message_id` now for this board.

**IMPORTANT**

Make sure to backup your DB before you change anything
